### ISSUE TITLE
add tool configuration via pyproject.toml

### ISSUE THREAD

**Issue by CagtayFabry** [CagtayFabry/pydeps2env#6]
Some configuration options would be nice, on the top of my head:

- list of dependencies to install via `pip`
- mapping of dependency names that differ for `pip` and `conda` (e.g. `weldx-widgets` -> `weldx_widgets`)

**Comment by marscher** [comment]
The pip list can also be provided by the env.yaml, right? So we would just require another loop for it and redirect the package names to pip.
This step has to occur after the mapping of the package names of course.

Another useful option could be to override the name of the environment. Also channels could be overridden by the config IMO.

**Comment by CagtayFabry** [comment]
> The pip list can also be provided by the env.yaml, right? So we would just require another loop for it and redirect the package names to pip.
This step has to occur after the mapping of the package names of course.

exactly the packages should just be placed in the pip section of the environment

> Another useful option could be to override the name of the environment. Also channels could be overridden by the config IMO.

yes setting default config values in a config file sounds good

**Comment by marscher** [comment]
Actually this issue is the blocker to install (new) environments during testing in the weldx repository.
